version: '4.0'

services:
  postgres:
    image: postgres:latest
    container_name: kgpspeedcubers
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kgpspeedcubers
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
